"""Add missing columns to users

Revision ID: 80212c9f3f64
Revises: 
Create Date: 2026-04-19 20:44:03.235046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80212c9f3f64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'gst_number')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.alter_column('orders', 'total_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'tax_amount')
    # ### end Alembic commands ###
