"""Add order items and adjust product schema

Revision ID: a7703faf8571
Revises: dc0dd6f555a5
Create Date: 2026-04-20 00:19:08.702631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7703faf8571'
down_revision: Union[str, Sequence[str], None] = 'dc0dd6f555a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('products', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('lot_price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('lot_size', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'price')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('products', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.drop_column('products', 'sku')
    op.drop_column('products', 'lot_size')
    op.drop_column('products', 'lot_price')
    op.drop_column('products', 'unit_price')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
